### ISSUE TITLE
As a Player I want to be able to see the list of available scenarios and select one of them to be loaded

### ISSUE THREAD

**Issue by JonathanTurnock** [JonathanTurnock/cfs-rts#11]
### A/C:
A User should be able to select **New Game** on the **Main Menu** and be presented with the list of **Available Scenarios**, they should then be able to click on a scenario and the game should load it.

### GQL Endpoints:
```
game_availableScenarios: [Scenario]!
game_loadScenario(id: ID!): Boolean!
```

### Tasks:
- [x] Have Angular Communicate with GraphQL using Apollo, https://www.apollographql.com/docs/angular/
- [x] Have ScenarioService in Angular get List of scenarios
- [x] Have Scenario be loaded when clicked on from the GUI
