### ISSUE TITLE
As a Player I want to be prompted to Join game if one is currently running

### ISSUE THREAD

**Issue by JonathanTurnock** [JonathanTurnock/cfs-rts#5]
### A/C
When a player lands on the landing page, they should not get the option to load a game if one is already running.
They should only be presented with a way to join the currently running game.

### Tasks

- [x] Add a Lock to the game where if one is currently running, a new game cannot be started
- [x] Make the NG app aware if the game is running or not at the time of connection
- [x] Render the appropriate scene option, New Game if one is not running or Join if one is running
